### ISSUE TITLE
Add a Rotary Encoder with Switch to Krake

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#5] opened 2024-06-01 13:32 UTC
_(On 20241302 rework this capturing better from a duplicate issue (#20) which was better written.)_  

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
A controller to navigate through the functions of Krake

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
adding an encoder to mocking krake 

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

## Original summary
 Feature Request:
A rotary encoder will enable development of a more interactive UI.

**Comment by nk25719** [comment] 2024-06-01 13:51
Let us consider the touch screen possibility and compare the advantage and disadvantages of each of these two features.

**Comment by nk25719** [comment] 2024-08-18 12:15
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
_Missing hardware that can control the UI of Krake_

**Describe the solution you'd like**
A clear and concise description of what you want to happen.
_Use Rotary knob switches that use a rotating mechanism to select,  send emergency and navigate  and establish connections in the UI of Krake._

**Comment by ForrestErickson** [comment] 2024-10-02 11:40
From the duplicate #20   

History of this issue is that it started in another repository, the **KiCad-esp32-6leds-2switches-1pj-circuit** here:
https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/issues/42

@nk25719 has created firmware at:
krake\Firmware\factoryTest\Rotarty Encoder\RotaryEncoderTest

This firmware interfaces the encoder at the following pins:
> // Define the GPIO pins for CLK, DT, and SW
> const int CLK = 14;   // Connected to the CLK pin of the encoder
> const int DT = 26;    // Connected to the DT pin of the encoder
> const int SW = 25;    // Connected to the SW (Switch) pin of the encoder


Here is a reference to an interrupt driven Rotary Encoder example:
https://www.instructables.com/How-to-Use-Rotary-Encoders-and-Interrupts-With-You/

Note issue #20 now closed.

**Comment by ForrestErickson** [comment] 2024-11-21 13:53
@nk25719 
As of 20241121 The schematic for the Krake has used GPIO25 and GPIO26 on the SPI input.

The Mocking Krake must be modified and rotary encoder firmware to test with the encoder on other pins.

**Comment by ForrestErickson** [comment] 2024-11-23 21:56
@nk25719 
Candidate JLCPCB part: https://jlcpcb.com/partdetail/Alpsalpine-EC11E18244AU/C202365

**Comment by nk25719** [comment] 2024-11-30 09:21
Schematic of the rotary encoder added to Krake: 
<img width="495" alt="image" src="https://github.com/user-attachments/assets/f31f612a-759a-494c-b83d-7f33264f28fb">

Rotary Encoder properties: 
<img width="537" alt="image" src="https://github.com/user-attachments/assets/cc820f68-1154-4fcf-8a9a-8f21857794cb">

**Comment by nk25719** [comment] 2024-11-30 09:22
cc: @ForrestErickson 

.
.

Closing.

**Comment by nk25719** [comment] 2024-12-21 14:31
Reopenning issue to: 

Schematic connections changed, capturing connections Dec 21 2024, 
Implement the Rotary encoder connections into MockingKrake 
Write firmware to test the current Rotary encoder connections before PWA subassembly release.

**Comment by nk25719** [comment] 2024-12-21 14:37
Schematic connections changed, capturing connections Dec 21, 2024.


<img width="574" alt="image" src="https://github.com/user-attachments/assets/acae77bd-b95a-41f1-866e-8198ed44309d" />

**Comment by nk25719** [comment] 2024-12-23 18:04
Connected the Rotery encoder to prototype Krake with it, 
pin connection as above shcematic.

**Comment by ForrestErickson** [comment] 2024-12-24 20:32
As of 20241224 we have added an encoder to the MockingKrake in Maryville and in Lebanon and demonstrated encoder and switch function on the pins as assigned in the Krake schematic.
There is an unresolved firmware problem with double incrementing on the encoder rotation but the hardware works.

Closing.

**Closed** 2024-12-26 19:05 UTC
Labels: enhancement
