### ISSUE TITLE
Add to PCB, Expansion Headders for Most / All of the ESP32 Kit pins.

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/krake#32] opened 2024-10-02 12:28 UTC
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
For development it may be necessary to connect to unused controller pins.
With out some kind of hole in the PCB to connect a probe or a wire this is often difficult or fragle and therefor error prone.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
Add expansion header paralleling most or all of the DSP32 kit pins. The header need not be populated at manufacturing time.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by ForrestErickson** [comment] 2024-10-02 12:31
Example of headers paralleling the Due controller on the OEDCS in schematic  
![image](https://github.com/user-attachments/assets/d0e2fad1-7946-4541-970f-c8ed4c2d1563)

Example of headers paralleling the Due controller on the OEDCS in PCB   
![image](https://github.com/user-attachments/assets/3930e2e1-989c-492c-9f08-c09516dfd37d)

Example of JLCPCB header parts  
![image](https://github.com/user-attachments/assets/72abaeff-ebb5-41d4-8f7e-714ee1464f98)

**Comment by nk25719** [comment] 2024-11-26 02:17
Duplicate of issue #68 

cc: @ForrestErickson

**Comment by nk25719** [comment] 2024-12-01 13:55
Implemented in schematic: 
<img width="233" alt="image" src="https://github.com/user-attachments/assets/8e279e67-7c0c-49e1-afcb-e3ac60b8a874">


Closing.

**Closed by nk25719** 2024-12-01 13:55 UTC
Labels: duplicate, enhancement
